apiVersion: v1
kind: Service
metadata:
  name: ignite-service
  namespace: ignite
  labels:
    app: ignite
spec:
  type: LoadBalancer
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: thinclients
      port: 10800
      targetPort: 10800
  selector:
    app: ignite
